nocond:
	@gcc peterson.c -o peterson.out
	@echo "MAKEFILE: Esecuzione senza controllo su postcondizione"
	@./peterson.out
cond:
	@gcc peterson.c -o peterson.out
	@echo "Makefile: Esecuzione con controllo su postcondizione"
	@./peterson.out true
